---
dependency:
  name: galaxy
  enabled: False

driver:
  name: docker

platforms:
  - name: ansible-role-spleeter-debian-10
    image: debian:10
  - name: ansible-role-spleeter-ubuntu-1604
    image: ubuntu:16.04
  - name: ansible-role-spleeter-ubuntu-1804
    image: ubuntu:18.04

lint: |
    yamllint .
    ansible-lint
    flake8

provisioner:
  name: ansible

verifier:
  name: testinfra
